#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libArcus
Version  : 3.6.0
Release  : 2
URL      : https://github.com/Ultimaker/libArcus/archive/3.6.0.tar.gz
Source0  : https://github.com/Ultimaker/libArcus/archive/3.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-3.0
Requires: libArcus-lib = %{version}-%{release}
Requires: libArcus-license = %{version}-%{release}
Requires: libArcus-python = %{version}-%{release}
Requires: libArcus-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : protobuf-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : sip-dev

%description
Arcus
=====
This library contains C++ code and Python3 bindings for creating a socket in a thread
and using this socket to send and receive messages based on the Protocol Buffers
library. It is designed to facilitate the communication between Cura and its
backend and similar code.

%package dev
Summary: dev components for the libArcus package.
Group: Development
Requires: libArcus-lib = %{version}-%{release}
Provides: libArcus-devel = %{version}-%{release}

%description dev
dev components for the libArcus package.


%package lib
Summary: lib components for the libArcus package.
Group: Libraries
Requires: libArcus-license = %{version}-%{release}

%description lib
lib components for the libArcus package.


%package license
Summary: license components for the libArcus package.
Group: Default

%description license
license components for the libArcus package.


%package python
Summary: python components for the libArcus package.
Group: Default
Requires: libArcus-python3 = %{version}-%{release}
Provides: libarcus-python

%description python
python components for the libArcus package.


%package python3
Summary: python3 components for the libArcus package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libArcus package.


%prep
%setup -q -n libArcus-3.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548352481
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1548352481
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libArcus
cp LICENSE %{buildroot}/usr/share/package-licenses/libArcus/LICENSE
cp cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/libArcus/cmake_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd
## install_append content
for src in %{buildroot}/usr/lib64/python*/site-packages; do dest=$(sed 's!/usr/lib64/!/usr/lib/!' <<< ${src}); mkdir -p $(dirname ${dest}); mv ${src} $(dirname ${dest}); done
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/Arcus/ArcusExport.h
/usr/include/Arcus/Error.h
/usr/include/Arcus/MessageTypeStore.h
/usr/include/Arcus/Socket.h
/usr/include/Arcus/SocketListener.h
/usr/include/Arcus/Types.h
/usr/lib64/cmake/Arcus/Arcus-targets-relwithdebinfo.cmake
/usr/lib64/cmake/Arcus/Arcus-targets.cmake
/usr/lib64/cmake/Arcus/ArcusConfig.cmake
/usr/lib64/cmake/Arcus/ArcusConfigVersion.cmake
/usr/lib64/libArcus.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libArcus.so.1.1.0
/usr/lib64/libArcus.so.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libArcus/LICENSE
/usr/share/package-licenses/libArcus/cmake_COPYING-CMAKE-SCRIPTS

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
